---

- include: supervisor-env.yml
- include: debian.yml
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
- include: redhat.yml
  when: (ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- name: decide mig_arch
  set_fact:
    mig_arch: amd64
  when: ansible_architecture == 'x86_64'
- set_fact:
    mig_sys: linux
  when: ansible_system == 'Linux'
- set_fact:
    mig_sys: windows
  when: ansible_system == 'Windows'

- name: decide mig_agent_bin
  set_fact:
    mig_agent_bin: "{{ mig_src }}/{{ mig_sys }}/{{ mig_arch }}/mig-agent-latest"
  when: ansible_system != 'Windows'
- set_fact:
    mig_agent_bin: "{{ mig_src }}/{{ mig_sys }}/{{ mig_arch }}/mig-agent-latest.exe"
  when: ansible_system == 'Windows'

- name: decide mig_agent_pkg
  set_fact:
    mig_agent_pkg: "{{ mig_src }}/mig-agent_latest-{{ ansible_architecture }}.deb"
    mig_agent_cfg: "{{ mig_src }}/conf/mig-agent.cfg"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
- set_fact:
    mig_agent_pkg: "{{ mig_src }}/mig-agent-latest-{{ ansible_architecture }}.rpm"
    mig_agent_cfg: "{{ mig_src }}/conf/mig-agent.cfg"
  when: (ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- block:
    - name: retrieve mig-agent archive if remote on orchestrator
      fetch: src="{{ mig_agent_pkg }}" dest=tmp/ flat=yes
      delegate_to: "{{ mig_servername }}"
    - name: retrieve mig agent cfg if remote on orchestrator
      fetch: src="{{ item }}" dest=tmp/ flat=yes
      with_items:
        - "{{ mig_agent_cfg }}"
        - /etc/mig/agent.key
        - /etc/mig/agent.crt
        - /etc/mig/ca.crt
      delegate_to: "{{ mig_servername }}"
    - name: push mig-agent on host
      copy: "src=tmp/{{ mig_agent_pkg | basename }} dest=/root/{{ mig_agent_pkg | basename }} mode=644"
      when: mig_api_host != 'localhost'
    - name: push mig cfg on host
      copy: "src=tmp/{{ item }} dest=/root/{{ item }} mode=400"
      with_items:
        - "{{ mig_agent_cfg | basename }}"
        - agent.key
        - agent.crt
        - ca.crt
    - set_fact:
        mig_agent_pkg: "/root/{{ mig_agent_pkg | basename }}"
        mig_agent_cfg: "/root/{{ mig_agent_cfg | basename }}"
  when: mig_api_host != 'localhost'

## FIXME! handle package update? latest not supported for pkg file
- name: apt | mig-agent install
  apt: deb="{{ mig_agent_pkg }}" state=present
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
- name: yum | mig-agent install
  yum: name="{{ mig_agent_pkg }}" state=present
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

## debian /agent_install.sh
- name: get mig-agent path
  shell: "ls /sbin/mig-agent-*"
  changed_when: false
  register: migagentpath
- name: check mig-agent permissions
  file: dest="{{ migagentpath.stdout }}" mode=0500 owner=root group=root state=file
- name: symlink last mig-agent
  file: src="{{ migagentpath.stdout }}" dest=/sbin/mig-agent state=link

- file: dest=/etc/mig state=directory mode=0750
## FIXME! builtin config seems incorrect
- stat: path={{ mig_agent_cfg }}
  register: macfg
- debug: var=macfg
- name: setting separate mig-agent config file
  copy:
    src: "{{ item.s }}"
    dest: "{{ item.d }}"
    mode: '0400'
    remote_src: true
  with_items:
   - { s: "{{ mig_agent_cfg }}", d: /etc/mig/mig-agent.cfg }
   - { s: /root/agent.key, d: /etc/mig/agent.key }
   - { s: /root/agent.crt, d: /etc/mig/agent.crt }
   - { s: /root/ca.crt, d: /etc/mig/ca.crt }
  notify:
    - restart supervisor

- name: set supervisor config to manage MIG client
  template: src=supervisord-migagent.ini dest={{ supervisor_confdir }}/migagent.{{ supervisor_ext }} mode=0644
  notify:
    - restart supervisor


