---

- set_fact:
    supervisor_confdir: /etc/supervisor/conf.d
    supervisor_ext: conf
    supervisor_service: supervisor
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- set_fact:
    supervisor_confdir: /etc/supervisord.d
    supervisor_ext: ini
    supervisor_service: supervisord
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
